---
title: "maps"
author: "Cassidy Bargell"
date: "4/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rtweet)
library(httpuv)
library(gtrendsR)
library(lubridate)
library(maps)
library(pals)
library(viridis)
library(scico)
library(ggrepel)
library(tidytext)
data("stop_words")
```

```{r google}

# Find initial google search trends on rugby 

google_rugby <- gtrends(c("rugby"), geo = c("US"),
                        gprop = "web", time = "all")


# Interest by region tibble to plot

rugby_interest_by_region <- as_tibble(google_rugby$interest_by_region)
rugby_interest_by_region <- rugby_interest_by_region %>% 
  mutate(region = str_to_lower(location))

# Create map of US states

states_map <- ggplot2::map_data("state")


# Join data

rugby_merged <- merge(states_map, rugby_interest_by_region, by = "region")
rugby_merged <- rugby_interest_by_region %>% dplyr::left_join(x = ., 
                                                            y = states_map, 
                                                            by = "region")

saveRDS(rugby_merged, file = "sport-perceptions/raw-data/rugby_merged.RDS")

# Create map theme so clean-up is easier

("milestone-6/map_theme.R")

map_theme = function() {
    theme(axis.title = element_blank()) +
    theme(axis.text = element_blank()) +
    theme(axis.ticks = element_blank()) + 
    theme(legend.title = element_blank()) +
  theme(panel.grid.major = element_blank())
}

# Plot map 

plot_rgsearch <- ggplot(rugby_merged, aes(x = long, y = lat)) +
  geom_polygon(aes(group = group, 
                   fill = log(hits)), 
               colour = "white") +
  scale_fill_viridis_c(option = "plasma",
                       direction = -1) +
  theme_minimal() + 
  labs(title = "Google Search Hits for 'Rugby' Since 2004", 
       subtitle = "Search Hits Normalized to Compare Relative Popularity",
       caption = "Google Trends: Search results are normalized to the time and
       location of a query. Each data point is divided by the total searches of
       the geography and time range it represents to compare relative popularity.") +
  map_theme()
```

```{r google}

# Create RDS that can be easily downloaded into the shiny app to render plots.

google_football <- gtrends(c("football"), 
                         geo = c("US"),
                        gprop = "web", time = "all")

google_soccer <- gtrends(c("soccer"), 
                         geo = c("US"),
                        gprop = "web", time = "all")

google_hockey <- gtrends(c("hockey"), 
                         geo = c("US"),
                        gprop = "web", time = "all")

google_basketball <- gtrends(c("basketball"), 
                         geo = c("US"),
                        gprop = "web", time = "all")

google_rugby <- gtrends(c("rugby"), 
                         geo = c("US"),
                        gprop = "web", time = "all")

google_concussion <- gtrends(c("concussion"),
                                geo = c("US"),
                                gprop = "web", time = "all")

google_cte <- gtrends(c("CTE"), 
                         geo = c("US"),
                        gprop = "web", time = "all")

google_tbi <- gtrends(c("TBI"), 
                         geo = c("US"),
                        gprop = "web", time = "all")

# Some tibbles may have characters for hits because there are hits <1, in order to
# full join will change hits column to integer

g_football <- as.data.frame(google_football$interest_over_time)
g_hockey <- as.data.frame(google_hockey$interest_over_time)
g_rugby <- as.data.frame(google_rugby$interest_over_time)
g_soccer <- as.data.frame(google_soccer$interest_over_time)
g_basketball <- as.data.frame(google_basketball$interest_over_time)
g_concussion <- as.data.frame(google_concussion$interest_over_time)
g_cte <- as.data.frame(google_cte$interest_over_time)
g_tbi <- as.data.frame(google_tbi$interest_over_time)

# Join everything and make RDS file

g_search <- g_football %>%
  full_join(g_hockey, by = c("keyword", "date", "hits")) %>%
  full_join(g_rugby, by = c("keyword", "date", "hits")) %>%
  full_join(g_soccer, by = c("keyword", "date", "hits")) %>%
  full_join(g_basketball, by = c("keyword", "date", "hits")) %>%
  full_join(g_concussion, by = c("keyword", "date", "hits")) %>%
  full_join(g_cte, by = c("keyword", "date", "hits")) %>%
  full_join(g_tbi, by = c("keyword", "date", "hits"))

saveRDS(g_search, file = "sport-perceptions/raw-data/gtrend_search.RDS")

g_search %>%
  filter(keyword == "hockey") %>%
  ggplot(aes(date, hits, color = keyword)) + geom_path() + 
  labs(title = "Google Search Hits Over Time",
       x = "Date",
       y = "Hits (Normalized to Scale of 100)",
       color = "Search Term") +
  theme_classic()
```

```{r normalize to sport}

# Google search hits will be normalized to 100 based on highest hits day of the
# search terms you search for together in one call of gtrends. Want to add plots
# that show when concussion and cte and tbi are normalized to a sport search
# hit.

google_football2 <- gtrends(c("'football concussion'"), 
                         geo = c("US"),
                        gprop = "web", time = "all")

google_soccer2 <- gtrends(c("'soccer concussion'"), 
                         geo = c("US"),
                        gprop = "web", time = "all")

google_hockey2 <- gtrends(c("'hockey concussion'"), 
                         geo = c("US"),
                        gprop = "web", time = "all")

google_basketball2 <- gtrends(c("'basketball concussion'"), 
                         geo = c("US"),
                        gprop = "web", time = "all")

google_rugby2 <- gtrends(c("'rugby concussion'"), 
                         geo = c("US"),
                        gprop = "web", time = "all")

g_football2 <- as.data.frame(google_football2$interest_over_time)
g_hockey2 <- as.data.frame(google_hockey2$interest_over_time)
g_rugby2 <- as.data.frame(google_rugby2$interest_over_time)
g_soccer2 <- as.data.frame(google_soccer2$interest_over_time)
g_basketball2 <- as.data.frame(google_basketball2$interest_over_time)

# Join everything and make RDS file

g_search2 <- g_football2 %>%
  full_join(g_hockey2, by = c("keyword", "date", "hits")) %>%
  full_join(g_rugby2, by = c("keyword", "date", "hits")) %>%
  full_join(g_soccer2, by = c("keyword", "date", "hits")) %>%
  full_join(g_basketball2, by = c("keyword", "date", "hits")) 

saveRDS(g_search2, file = "sport-perceptions/raw-data/gtrend_search2.RDS")

g_search2 %>%
  filter(keyword == "'rugby concussion'") %>%
                ggplot(aes(date, hits, color = keyword)) + geom_path() +
                labs(title = "Google Search Hits Over Time",
                     x = "Date",
                     y = "Hits (Normalized to Scale of 100)",
                     color = "Search Term") +
                theme_classic()

```

