---
title: "twitter graphics"
author: "Cassidy Bargell"
date: "4/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rtweet)
library(httpuv)
library(gtrendsR)
library(lubridate)
library(maps)
library(pals)
library(viridis)
library(scico)
library(ggrepel)
library(infer)
library(purrr)
library(tidyr)
library(stringr)
library(tidytext)
library(widyr)
data("stop_words")
```

```{r read in}

# read in RDS files to work with to avoid rate limits on twitter

football <- readRDS("sport-perceptions/raw-data/football.RDS")
rugby <- readRDS("sport-perceptions/raw-data/rugby.RDS")
nfl_tml <- readRDS("sport-perceptions/raw-data/nfl_tml.RDS")
wr_tml <- readRDS("sport-perceptions/raw-data/wr_tml.RDS")
sr_tml <- readRDS("sport-perceptions/raw-data/sr_tml.RDS")
usarugby_tml <- readRDS("sport-perceptions/raw-data/usarugby_tml.RDS")
usahockey_tml <- readRDS("sport-perceptions/raw-data/usahockey_tml.RDS")
ussoccer_tml <- readRDS("sport-perceptions/raw-data/ussoccer_tml.RDS")
hockey <- readRDS("sport-perceptions/raw-data/hockey.RDS")
soccer <- readRDS("sport-perceptions/raw-data/soccer.RDS")
nba_tml <- readRDS("sport-perceptions/raw-data/nba_tml.RDS")
nhl_tml <- readRDS("sport-perceptions/raw-data/nhl_tml.RDS")
basketball <- readRDS("sport-perceptions/raw-data/basketball.RDS")
ncaa_foot_tml <- readRDS("sport-perceptions/raw-data/ncaa_foot_tml.RDS")
ncaa_tml <- readRDS("sport-perceptions/raw-data/ncaa_tml.RDS")
ncaa_research <- readRDS("sport-perceptions/raw-data/research_tml.RDS")

# Only want to use a sample of 4,000 of the tweets, as there are generally less
# rugby tweets than football in the US, so a random sample of most recent 4,000
# in the tibbles scrapped will then be used and bootstrap re-sampled.

football <- football %>%
  slice(1:4000)

rugby <- rugby %>%
  slice(1:4000)
```


```{r football tweet words}
football %>%
  select(created_at, text, favorite_count, quote_count, retweet_count, reply_count) 

# Remove urls in tweets, and create list of words I want to search the tweets
# for. Capitalization are recognized separately.

football$stripped_text <- gsub("http.*","",  football$text)
football$stripped_text <- gsub("https.*","", football$stripped_text)

football_clean <- football %>%
  select(stripped_text) %>%
  unnest_tokens(word, stripped_text) 

# Get rid of pre-loaded group of words that have no context

football_clean <- football_clean %>%
  anti_join(stop_words, by = "word")
```

```{r cleaning function}

# Create function for cleaning the tweet words based on what I did above

tweetclean <- function(tib) {

tib$stripped_text <- gsub("http.*","",  tib$text)
tib$stripped_text <- gsub("https.*","", tib$stripped_text)

tib_clean <- tib %>%
  select(stripped_text) %>%
  unnest_tokens(word, stripped_text) 

tib_clean <- tib_clean %>%
  anti_join(stop_words, by = "word")
}


football_clean <- tweetclean(football)
sr_clean <- tweetclean(sr_tml)
wr_clean <- tweetclean(wr_tml)
rugby_clean <- tweetclean(rugby)
usarugby_tml_clean <- tweetclean(usarugby_tml)
usahockey_tml_clean <- tweetclean(usahockey_tml)
ussoccer_tml_clean <- tweetclean(ussoccer_tml)
hockey_clean <- tweetclean(hockey)
soccer_clean <- tweetclean(soccer)
nfl_tml_clean <- tweetclean(nfl_tml)
nba_tml_clean <- tweetclean(nba_tml)
nhl_tml_clean <- tweetclean(nhl_tml)
basketball_clean <- tweetclean(basketball)
ncaafoot_clean <- tweetclean(ncaa_foot_tml)
ncaa_clean <- tweetclean(ncaa_tml)
research_clean <- tweetclean(ncaa_research)
```

```{r}

# Find proportion of tweets that contain one of the key words. Use function to
# make process cleaner.

proportion_words <- function(tib){
  
tib$stripped_text <- gsub("http.*","",  tib$text)
tib$stripped_text <- gsub("https.*","", tib$stripped_text)

  tib %>%
  mutate(has = ifelse(str_detect(stripped_text, regex("injury", ignore_case = TRUE)), 1, 0)) %>%
  mutate(has = ifelse(str_detect(stripped_text, regex("injuries", ignore_case = TRUE)), 1, 0)) %>%
  mutate(has = ifelse(str_detect(stripped_text, regex("concussion", ignore_case = TRUE)), 1, 0)) %>%
  mutate(has = ifelse(str_detect(stripped_text, regex("concussions", ignore_case = TRUE)), 1, 0)) %>%
  mutate(has = ifelse(str_detect(stripped_text, regex("cte", ignore_case = TRUE)), 1, 0)) %>%
  count(has) %>%
  mutate(total = sum(n)) %>%
  filter(has == 1) %>%
   mutate(prop = ((n / total)) * 100)
}

foot_prop <- proportion_words(football)
rugby_prop <- proportion_words(rugby)
sr_prop <- proportion_words(sr_tml)
wr_prop <- proportion_words(wr_tml)
nfl_prop <- proportion_words(nfl_tml)
usarugby_prop <- proportion_words(usarugby_tml) 
usahockey_prop <- proportion_words(usahockey_tml)
ussoccer_prop <- proportion_words(ussoccer_tml)
hockey_prop <- proportion_words(hockey)
soccer_prop <- proportion_words(soccer)
nba_prop <- proportion_words(nba_tml)
nhl_prop <- proportion_words(nhl_tml)
basketball_prop <- proportion_words(basketball)
ncaafoot_prop <- proportion_words(ncaa_foot_tml)
ncaa_prop <- proportion_words(ncaa_tml)
research_prop <- proportion_words(ncaa_research)
```

```{r bootstrap resample}

# Bootstrap re-sample the football data

bootstrap_football <- football %>%
  rep_sample_n(size = 4000, replace = TRUE, reps = 1000) %>%
  group_by(replicate) %>%
  proportion_words() %>%
  ungroup() %>%
  pull(prop) %>%
  quantile(c(0.025, 0.975))

file.create("bootstrap_football.RDS")
saveRDS(bootstrap_football, file = "sport-perceptions/raw-data/bootstrap_football.RDS")

# Create function to bootstrap the words more easily

bootstrap_prop <- function(tib){
  tib %>%
  rep_sample_n(size = 4000, replace = TRUE, reps = 1000) %>%
  group_by(replicate) %>%
  proportion_words() %>%
  ungroup() %>%
  pull(prop) %>%
  quantile(c(0.025, 0.975))
}

# Bootstrap resample all of the different sources

bootstrap_rugby <- bootstrap_prop(rugby)
bootstrap_sr <- bootstrap_prop(sr_tml)
bootstrap_wr <- bootstrap_prop(wr_tml)
bootstrap_nfl <- bootstrap_prop(nfl_tml)
bootstrap_usarugby <- bootstrap_prop(usarugby_tml)
bootstrap_usahockey <- bootstrap_prop(usahockey_tml)
bootstrap_ussoccer <- bootstrap_prop(ussoccer_tml)
bootstrap_soccer <- bootstrap_prop(soccer)
bootstrap_hockey <- bootstrap_prop(hockey)
bootstrap_basketball <- bootstrap_prop(basketball)
bootstrap_nba <- bootstrap_prop(nba_tml)
bootstrap_nhl <- bootstrap_prop(nhl_tml)
bootstrap_ncaafoot <- bootstrap_prop(ncaa_foot_tml)
bootstrap_ncaa <- bootstrap_prop(ncaa_tml)
bootstrap_research <- bootstrap_prop(ncaa_research)

file.create("bootstrap_basketball.RDS")
saveRDS(bootstrap_basketball, file = "sport-perceptions/raw-data/bootstrap_basketball.RDS")

file.create("bootstrap_nba.RDS")
saveRDS(bootstrap_nba, file = "sport-perceptions/raw-data/bootstrap_nba.RDS")

file.create("bootstrap_nhl.RDS")
saveRDS(bootstrap_nhl, file = "sport-perceptions/raw-data/bootstrap_nhl.RDS")

file.create("bootstrap_rugby.RDS")
saveRDS(bootstrap_rugby, file = "sport-perceptions/raw-data/bootstrap_rugby.RDS")

file.create("bootstrap_sr.RDS")
saveRDS(bootstrap_sr, file = "sport-perceptions/raw-data/bootstrap_sr.RDS")

file.create("bootstrap_wr.RDS")
saveRDS(bootstrap_wr, file = "sport-perceptions/raw-data/bootstrap_wr.RDS")

file.create("bootstrap_nfl.RDS")
saveRDS(bootstrap_nfl, file = "sport-perceptions/raw-data/bootstrap_nfl.RDS")

file.create("bootstrap_usarugby.RDS")
saveRDS(bootstrap_usarugby, file = "sport-perceptions/raw-data/bootstrap_usarugby.RDS")

file.create("bootstrap_usahockey.RDS")
saveRDS(bootstrap_usahockey, file = "sport-perceptions/raw-data/bootstrap_usahockey.RDS")

file.create("bootstrap_ussoccer.RDS")
saveRDS(bootstrap_ussoccer, file = "sport-perceptions/raw-data/bootstrap_ussoccer.RDS")

file.create("bootstrap_soccer.RDS")
saveRDS(bootstrap_soccer, file = "sport-perceptions/raw-data/bootstrap_soccer.RDS")

file.create("bootstrap_hockey.RDS")
saveRDS(bootstrap_hockey, file = "sport-perceptions/raw-data/bootstrap_hockey.RDS")

file.create("bootstrap_ncaafoot.RDS")
saveRDS(bootstrap_ncaafoot, file = "sport-perceptions/raw-data/bootstrap_ncaafoot.RDS")

file.create("bootstrap_ncaa.RDS")
saveRDS(bootstrap_ncaa, file = "sport-perceptions/raw-data/bootstrap_ncaa.RDS")

file.create("bootstrap_research.RDS")
saveRDS(bootstrap_research, file = "sport-perceptions/raw-data/bootstrap_research.RDS")
```


```{r plots}

# Add column with sport/organization to keep track of rows with joines

football_error <- as_tibble(bootstrap_football) %>%
  mutate(error = c("lower", "upper")) %>%
  pivot_wider(names_from = error, values_from = value) %>%
  mutate(sport = "football")

# Make function to make it easier

error <- function(tib){
  as_tibble(tib) %>%
  mutate(error = c("lower", "upper")) %>%
  pivot_wider(names_from = error, values_from = value) 
}

# Make confidence interval table for all the variables

rugby_error <- error(bootstrap_rugby) %>%
  mutate(sport = "rugby")
sr_error <- error(bootstrap_sr) %>%
  mutate(organization = "superrugby")
wr_error <- error(bootstrap_wr) %>%
  mutate(organization = "worldrugby")
nfl_error <- error(bootstrap_nfl) %>%
  mutate(organization = "nfl")
usarugby_error <- error(bootstrap_usarugby) %>%
  mutate(organization = "usarugby")
usahockey_error <- error(bootstrap_usahockey) %>%
  mutate(organization = "usahockey")
ussoccer_error <- error(bootstrap_ussoccer) %>%
  mutate(organization = "ussoccer")
hockey_error <- error(bootstrap_hockey) %>%
  mutate(sport = "hockey")
soccer_error <- error(bootstrap_soccer) %>%
  mutate(sport = "soccer")
nba_error <- error(bootstrap_nba) %>%
  mutate(organization = "nba")
nhl_error <- error(bootstrap_nhl) %>%
  mutate(organization = "nhl")
basketball_error <- error(bootstrap_basketball) %>%
  mutate(sport = "basketball")
football_error <- error(bootstrap_football) %>%
  mutate(sport = "football")
ncaafoot_error <- error(bootstrap_ncaafoot) %>%
  mutate(organization = "ncaafoot")
ncaa_error <- error(bootstrap_ncaa) %>%
  mutate(organization = "ncaa")
research_error <- error(bootstrap_research) %>%
  mutate(organization = "research")

foot_prop <- foot_prop %>%
  mutate(sport = "football") 
rugby_prop <- rugby_prop %>%
  mutate(sport = "rugby")
sr_prop <- sr_prop %>%
  mutate(organization = "superrugby")
wr_prop <- wr_prop %>%
  mutate(organization = "worldrugby")
nfl_prop <- nfl_prop %>%
  mutate(organization = "nfl")
usarugby_prop <- usarugby_prop %>%
  mutate(organization = "usarugby")
usahockey_prop <- usahockey_prop %>%
  mutate(organization = "usahockey")
ussoccer_prop <- ussoccer_prop %>%
  mutate(organization = "ussoccer")
hockey_prop <- hockey_prop %>%
  mutate(sport = "hockey")
soccer_prop <- soccer_prop %>%
  mutate(sport = "soccer")
nba_prop <- nba_prop %>%
  mutate(organization = "nba") 
nhl_prop <- nhl_prop %>%
  mutate(organization = "nhl")
basketball_prop <- basketball_prop %>%
  mutate(sport = "basketball")
ncaafoot_prop <- ncaafoot_prop %>%
  mutate(organization = "ncaafoot")
ncaa_prop <- ncaa_prop %>%
  mutate(organization = "ncaa")
research_prop <- research_prop %>%
  mutate(organization = "research")

sports_prop <- foot_prop %>%
  full_join(rugby_prop, by = c("prop", "n", "total", "has", "sport")) %>%
  full_join(hockey_prop, by = c("prop", "n", "total", "has", "sport")) %>%
  full_join(soccer_prop, by = c("prop", "n", "total", "has", "sport")) %>%
  full_join(basketball_prop, by = c("prop", "n", "total", "has", "sport"))

sports_error <- football_error %>%
  full_join(rugby_error, by = c("lower", "upper", "sport")) %>%
  full_join(soccer_error, by = c("lower", "upper", "sport")) %>%
  full_join(hockey_error, by = c("lower", "upper", "sport")) %>%
  full_join(basketball_error, by = c("lower", "upper", "sport"))

sports <- sports_prop %>%
  full_join(sports_error, by = "sport")

organ_prop <- nfl_prop %>%
  full_join(usarugby_prop, by = c("prop", "n", "total", "has", "organization")) %>%
  full_join(ussoccer_prop, by = c("prop", "n", "total", "has", "organization")) %>%
  full_join(usahockey_prop, by = c("prop", "n", "total", "has", "organization")) %>%
  full_join(wr_prop, by = c("prop", "n", "total", "has", "organization")) %>%
  full_join(sr_prop, by = c("prop", "n", "total", "has", "organization")) %>%
  full_join(nba_prop, by = c("prop", "n", "total", "has", "organization")) %>%
  full_join(nhl_prop, by = c("prop", "n", "total", "has", "organization")) %>%
  full_join(ncaafoot_prop, by = c("prop", "n", "total", "has", "organization")) %>%
  full_join(ncaa_prop, by = c("prop", "n", "total", "has", "organization")) %>%
  full_join(research_prop, by = c("prop", "n", "total", "has", "organization")) 

organ_error <- nfl_error %>%
  full_join(usarugby_error, by = c("lower", "upper", "organization")) %>%
  full_join(ussoccer_error, by = c("lower", "upper", "organization")) %>%
  full_join(usahockey_error, by = c("lower", "upper", "organization")) %>%
  full_join(wr_error, by = c("lower", "upper", "organization")) %>%
  full_join(sr_error, by = c("lower", "upper", "organization")) %>%
  full_join(nba_error, by = c("lower", "upper", "organization")) %>%
  full_join(nhl_error, by = c("lower", "upper", "organization")) %>%
  full_join(ncaafoot_error, by = c("lower", "upper", "organization")) %>%
  full_join(ncaa_error, by = c("lower", "upper", "organization")) %>%
  full_join(research_error, by = c("lower", "upper", "organization")) 

organ <- organ_prop %>%
  full_join(organ_error, by = "organization") %>%
  mutate(sport = ifelse(organization == "nfl" |
                          organization == "ncaafoot", "football", 
                        ifelse(organization == "nhl" |
                                 organization == "usahockey", "hockey", 
                               ifelse(organization == "ussoccer", "soccer", 
                                      ifelse(organization == "usarugby" | 
                                               organization ==  "worldrugby" |
                                               organization == "superrugby", "rugby", 
                                             ifelse(organization == "nba", "basketball", 
                                                    ifelse(organization == "ncaa" |
                                                             organization == "research", "all", NA)))))))

file.create("sports.RDS")
saveRDS(sports, file = "sport-perceptions/raw-data/sports.RDS")

file.create("organ.RDS")
saveRDS(organ, file = "sport-perceptions/raw-data/organ.RDS")

sports <- read_rds("sport-perceptions/raw-data/sports.RDS")

ggplot(sports, aes(x = sport, y = prop, fill = sport)) + geom_col() + 
  geom_errorbar(aes(x = sport, ymin = lower, ymax = upper)) + 
  theme_classic() + 
  theme(legend.position = "none") + 
  labs(title = "Proportion of Sports Tweet Containing Words Related to Injury",
       subtitle = "Words Searched For: concussion(s), injury(ies), CTE",
       caption = "From sample of 4,000 random tweets containing reference to the specific sport, scraped on 4/22/20
       Error bars = 95% confidence interval",
       x = "Sport", 
       y = "Proportion (in %)") 

ggplot(organ, aes(x = organization, y = prop, fill = organization)) + geom_col() + 
  geom_errorbar(aes(x = organization, ymin = lower, ymax = upper), width=0.5, size=0.5,) + 
  theme_classic() + 
  theme(legend.position = "none") + 
  labs(title = "Proportion of Sports Tweet Containing Words Related to Injury",
       subtitle = "Words Searched For: concussion(s), injury(ies), CTE",
       caption = "3,200 most recent tweets from a given organization's verified twitter account, scraped on 4/22/20
       Error bars = 95% confidence interval",
       x = "Organization", 
       y = "Proportion (in %)")
```
```{r}

# Create fully merged tibble, add sports column to everything to join by 

merged <- sports %>%
  full_join(organ, by = c("has", "n", "total", "prop", "lower", "upper", "sport")) %>%
  mutate(organization = ifelse(is.na(organization), sport, organization))

file.create("merged.RDS")
saveRDS(merged, file = "sport-perceptions/raw-data/merged.RDS")

merged %>% filter(sport == "football") %>%
        ggplot(aes(x = organization, y = prop, fill = organization)) + geom_col()
```

```{r}
# Want to be able to display all the tweets that contain one of the key words I
# am searching for on my shiny app.

library(stringr)
library(dplyr)

football$stripped_text <- gsub("http.*","",  football$text)
football$stripped_text <- gsub("https.*","", football$stripped_text)

foot_cw <- football %>%
  mutate(has_injury = ifelse(str_detect(stripped_text, 
                                        regex("injury", ignore_case = TRUE)), 1, 0)) %>%
  mutate(has_injuries = ifelse(str_detect(stripped_text, 
                                          regex("injuries", ignore_case = TRUE)), 1, 0)) %>%
  mutate(has_concussion = ifelse(str_detect(stripped_text, 
                                            regex("concussion", ignore_case = TRUE)), 1, 0)) %>%
  mutate(has_concussions = ifelse(str_detect(stripped_text, 
                                            regex("concussions", ignore_case = TRUE)), 1, 0)) %>%
  mutate(has_cte = ifelse(str_detect(stripped_text, 
                                            regex("cte", ignore_case = TRUE)), 1, 0)) %>%
  select(screen_name, stripped_text, 
         has_injuries, has_injury, has_concussion, has_concussions, has_cte) %>%
  filter(has_injuries == 1 | has_injury == 1 | has_concussion == 1 | has_concussions == 1 | has_cte == 1)
           
contains_word <- function(tib, sp){
  
tib$stripped_text <- gsub("http.*","",  tib$text)
tib$stripped_text <- gsub("https.*","", tib$stripped_text)
  
tib %>%
  mutate(has_injury = ifelse(str_detect(stripped_text, 
                                        regex("injury", ignore_case = TRUE)), 1, 0)) %>%
  mutate(has_injuries = ifelse(str_detect(stripped_text, 
                                          regex("injuries", ignore_case = TRUE)), 1, 0)) %>%
  mutate(has_concussion = ifelse(str_detect(stripped_text, 
                                            regex("concussion", ignore_case = TRUE)), 1, 0)) %>%
  mutate(has_concussions = ifelse(str_detect(stripped_text, 
                                            regex("concussions", ignore_case = TRUE)), 1, 0)) %>%
  mutate(has_cte = ifelse(str_detect(stripped_text, 
                                            regex("cte", ignore_case = TRUE)), 1, 0)) %>%
  select(screen_name, stripped_text, 
         has_injuries, has_injury, has_concussion, has_concussions, has_cte) %>%
  filter(has_injuries == 1 | has_injury == 1 | has_concussion == 1 | 
           has_concussions == 1 | has_cte == 1) %>%
    select(screen_name, stripped_text) %>%
    mutate(choice = sp)
}

rugby_cw <- contains_word(rugby, "rugby")
football_cw <- contains_word(football, "football")
hockey_cw <- contains_word(hockey, "hockey")
soccer_cw <- contains_word(soccer, "soccer")
basketball_cw <- contains_word(basketball, "basketball")
nfl_cw <- contains_word(nfl_tml, "nfl")
nhl_cw <- contains_word(nhl_tml, "nhl")
nba_cw <- contains_word(nba_tml, "nba")
ncaa_cw <- contains_word(ncaa_tml, "ncaa")
research_cw <- contains_word(ncaa_research, "ncaaresearch")
ncaafoot_cw <- contains_word(ncaa_foot_tml, "ncaafoot")
usarugby_cw <- contains_word(usarugby_tml, "usarugby")
sr_cw <- contains_word(sr_tml, "sr")
wr_cw <- contains_word(wr_tml, "wr")
ussoccer_cw <- contains_word(ussoccer_tml, "ussoccer")
usahockey_cw <- contains_word(usahockey_tml, "usahockey")

tweets <- football_cw %>%
  full_join(rugby_cw, by = c("screen_name", "stripped_text", "choice")) %>%
  full_join(hockey_cw, by = c("screen_name", "stripped_text", "choice")) %>%
  full_join(soccer_cw, by = c("screen_name", "stripped_text", "choice")) %>%
  full_join(basketball_cw, by = c("screen_name", "stripped_text", "choice")) %>%
  full_join(nfl_cw, by = c("screen_name", "stripped_text", "choice")) %>%
  full_join(nhl_cw, by = c("screen_name", "stripped_text", "choice")) %>%
  full_join(nba_cw, by = c("screen_name", "stripped_text", "choice")) %>%
  full_join(ncaa_cw, by = c("screen_name", "stripped_text", "choice")) %>%
  full_join(research_cw, by = c("screen_name", "stripped_text", "choice")) %>%
  full_join(ncaafoot_cw, by = c("screen_name", "stripped_text", "choice")) %>%
  full_join(usarugby_cw, by = c("screen_name", "stripped_text", "choice")) %>%
  full_join(sr_cw, by = c("screen_name", "stripped_text", "choice")) %>%
  full_join(wr_cw, by = c("screen_name", "stripped_text", "choice")) %>%
  full_join(ussoccer_cw, by = c("screen_name", "stripped_text", "choice")) %>%
  full_join(usahockey_cw, by = c("screen_name", "stripped_text", "choice")) 

file.create("tweets.RDS")
saveRDS(tweets, file = "sport-perceptions/raw-data/tweets.RDS")
```




